<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
	<testsuite errors="0" failures="1" file="tests.py" name="tests.PostTestCase-20200501191048" skipped="0" tests="12" time="0.014" timestamp="2020-05-01T19:10:48">
		<testcase classname="tests.PostTestCase" file="module4/tests.py" line="246" name="test_task10_uncomment_templates" time="0.006" timestamp="2020-05-01T19:10:48">
			<system-out>
<![CDATA[]]>			</system-out>
			<system-err>
<![CDATA[]]>			</system-err>
		</testcase>
		<testcase classname="tests.PostTestCase" file="module4/tests.py" line="258" name="test_task11_admin_register_tag" time="0.001" timestamp="2020-05-01T19:10:48">
			<system-out>
<![CDATA[]]>			</system-out>
			<system-err>
<![CDATA[]]>			</system-err>
		</testcase>
		<testcase classname="tests.PostTestCase" file="module4/tests.py" line="282" name="test_task12_make_migrations" time="0.001" timestamp="2020-05-01T19:10:48">
			<system-out>
<![CDATA[]]>			</system-out>
			<system-err>
<![CDATA[]]>			</system-err>
		</testcase>
		<testcase classname="tests.PostTestCase" file="module4/tests.py" line="114" name="test_task1_tag_model_exists" time="0.001" timestamp="2020-05-01T19:10:48">
			<system-out>
<![CDATA[]]>			</system-out>
			<system-err>
<![CDATA[]]>			</system-err>
		</testcase>
		<testcase classname="tests.PostTestCase" file="module4/tests.py" line="132" name="test_task3_str_exists" time="0.001" timestamp="2020-05-01T19:10:48">
			<system-out>
<![CDATA[]]>			</system-out>
			<system-err>
<![CDATA[]]>			</system-err>
		</testcase>
		<testcase classname="tests.PostTestCase" file="module4/tests.py" line="136" name="test_task4_many_to_many_exists" time="0.001" timestamp="2020-05-01T19:10:48">
			<system-out>
<![CDATA[]]>			</system-out>
			<system-err>
<![CDATA[]]>			</system-err>
		</testcase>
		<testcase classname="tests.PostTestCase" file="module4/tests.py" line="192" name="test_task5_tag_view" time="0.001" timestamp="2020-05-01T19:10:48">
			<system-out>
<![CDATA[]]>			</system-out>
			<system-err>
<![CDATA[]]>			</system-err>
		</testcase>
		<testcase classname="tests.PostTestCase" file="module4/tests.py" line="198" name="test_task6_tag_view_title" time="0.001" timestamp="2020-05-01T19:10:48">
			<system-out>
<![CDATA[]]>			</system-out>
			<system-err>
<![CDATA[]]>			</system-err>
		</testcase>
		<testcase classname="tests.PostTestCase" file="module4/tests.py" line="203" name="test_task7_tag_view_find_posts" time="0.001" timestamp="2020-05-01T19:10:48">
			<system-out>
<![CDATA[]]>			</system-out>
			<system-err>
<![CDATA[]]>			</system-err>
		</testcase>
		<testcase classname="tests.PostTestCase" file="module4/tests.py" line="209" name="test_task8_add_tag_url" time="0.001" timestamp="2020-05-01T19:10:48">
			<system-out>
<![CDATA[]]>			</system-out>
			<system-err>
<![CDATA[]]>			</system-err>
		</testcase>
		<testcase classname="tests.PostTestCase" file="module4/tests.py" line="236" name="test_task9_url_reverser" time="0.001" timestamp="2020-05-01T19:10:48">
			<system-out>
<![CDATA[]]>			</system-out>
			<system-err>
<![CDATA[]]>			</system-err>
		</testcase>
		<testcase classname="tests.PostTestCase" file="module4/tests.py" line="125" name="test_task2_clean_method_exists" time="0.001" timestamp="2020-05-01T19:10:48">
			<failure message="Did you assign to `self.name` in the `clean` method?" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/home/roman/projects/pluralsightDjangoProj/python-django-models-authentication/module4/tests.py", line 130, in test_task2_clean_method_exists
    self.assertTrue(self.clean_assign_found, msg="Did you assign to `self.name` in the `clean` method?")
  File "/home/roman/projects/pluralsightDjangoProj/python-django-models-authentication/support/SimplerTestCase.py", line 12, in assertTrue
    self.fail(msg or (str(expr) + "is not True"))
AssertionError: Did you assign to `self.name` in the `clean` method?
]]>			</failure>
			<system-out>
<![CDATA[]]>			</system-out>
			<system-err>
<![CDATA[]]>			</system-err>
		</testcase>
	</testsuite>
</testsuites>
